spring:
  application:
    name: hello-consumer
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds : 100  #隔离超时时间设置
      circuitBreaker:
        sleepWindowInMilliseconds: 8000 #熔断器打开后的休眠时间窗口，到达该时间后，熔断器半开
      metrics:
        rollingStats:
          timeInMilliseconds : 16000 #熔断器计数滚动时间窗口值